### PR TITLE
Fix function type resolution with nested funcs

### LINKED ISSUE #57: Panic in isReturnedWithNonNilError
@ryanhall07 ran into this and debugged it to `isReturnedWithNonNilError`, I was able to come up with a small repro:

```go
type Params struct {
        Name string // required
}

func foo() {
        f := func() string {
                return Params{}.Name
        }
        fmt.Println(f())
}
```

Panic:
```
$ requiredfield ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x100271e60]

goroutine 600 [running]:
go.abhg.dev/requiredfield.(*enforcer).isReturnedWithNonNilError(0x10044c2e0?, {0x14007068400?, 0x14007af83c0?, 0x4?})
        /Users/prashant/go/pkg/mod/go.abhg.dev/requiredfield@v0.5.0/enforce.go:167 +0x140
go.abhg.dev/requiredfield.(*enforcer).visit(0x14003dacc30, {0x1004a5c40?, 0x14007b285c0}, {0x14007068400, 0x9, 0x10})
        /Users/prashant/go/pkg/mod/go.abhg.dev/requiredfield@v0.5.0/enforce.go:87 +0x228
go.abhg.dev/requiredfield.run.(*enforcer).Enforce.func1({0x1004a5c40?, 0x14007b285c0?}, 0x0?, {0x14007068400?, 0x10044b6e0?, 0x0?})
        /Users/prashant/go/pkg/mod/go.abhg.dev/requiredfield@v0.5.0/enforce.go:31 +0x3c
# truncated, see details for full panic
```

<details>

```
$ requiredfield ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x100271e60]

goroutine 600 [running]:
go.abhg.dev/requiredfield.(*enforcer).isReturnedWithNonNilError(0x10044c2e0?, {0x14007068400?, 0x14007af83c0?, 0x4?})
        /Users/prashant/go/pkg/mod/go.abhg.dev/requiredfield@v0.5.0/enforce.go:167 +0x140
go.abhg.dev/requiredfield.(*enforcer).visit(0x14003dacc30, {0x1004a5c40?, 0x14007b285c0}, {0x14007068400, 0x9, 0x10})
        /Users/prashant/go/pkg/mod/go.abhg.dev/requiredfield@v0.5.0/enforce.go:87 +0x228
go.abhg.dev/requiredfield.run.(*enforcer).Enforce.func1({0x1004a5c40?, 0x14007b285c0?}, 0x0?, {0x14007068400?, 0x10044b6e0?, 0x0?})
        /Users/prashant/go/pkg/mod/go.abhg.dev/requiredfield@v0.5.0/enforce.go:31 +0x3c
golang.org/x/tools/go/ast/inspector.(*Inspector).WithStack(0x14007b24588, {0x1006799d0?, 0x303dacc28?, 0x147873dc0?}, 0x14003dacc48)
        /Users/prashant/go/pkg/mod/golang.org/x/tools@v0.30.0/go/ast/inspector/inspector.go:179 +0x160
go.abhg.dev/requiredfield.(*enforcer).Enforce(...)
        /Users/prashant/go/pkg/mod/go.abhg.dev/requiredfield@v0.5.0/enforce.go:26
go.abhg.dev/requiredfield.run(0x14007196b60)
        /Users/prashant/go/pkg/mod/go.abhg.dev/requiredfield@v0.5.0/analyzer.go:64 +0x13c
golang.org/x/tools/go/analysis/checker.(*Action).execOnce.func3(...)
        /Users/prashant/go/pkg/mod/golang.org/x/tools@v0.30.0/go/analysis/checker/checker.go:367
golang.org/x/tools/go/analysis/checker.(*Action).execOnce(0x140060f78c0)
        /Users/prashant/go/pkg/mod/golang.org/x/tools@v0.30.0/go/analysis/checker/checker.go:388 +0x920
sync.(*Once).doSlow(0x0?, 0x10000010067f460?)
        /Users/prashant/.local/share/mise/installs/go/1.24.5/src/sync/once.go:78 +0xf0
sync.(*Once).Do(...)
        /Users/prashant/.local/share/mise/installs/go/1.24.5/src/sync/once.go:69
golang.org/x/tools/go/analysis/checker.(*Action).exec(...)
        /Users/prashant/go/pkg/mod/golang.org/x/tools@v0.30.0/go/analysis/checker/checker.go:265
golang.org/x/tools/go/analysis/checker.execAll.func1(0x1004a65a0?)
        /Users/prashant/go/pkg/mod/golang.org/x/tools@v0.30.0/go/analysis/checker/checker.go:253 +0x50
created by golang.org/x/tools/go/analysis/checker.execAll in goroutine 1
        /Users/prashant/go/pkg/mod/golang.org/x/tools@v0.30.0/go/analysis/checker/checker.go:259 +0x14c
```

</details>

It seems like there's a couple of issues:
 * Functions that don't have returns have `ftype.Results = nil`, which panics here:
https://github.com/abhinav/requiredfield/blob/8f49d1f3bebbe797a2c8c33dc548d1192edd5ad5/enforce.go#L166-L168

 * It seems like the return --> matching function signature matching is incorrect since the return is inside of `func() string` but it seems to be looking at `func foo()`

### PR DESCRIPTION
**Pull request by prashantv**
Fixes #57

isReturnedWithNonNilError walks up from the return statement to find the matching function type, but it doesn't `break` when it finds the closest function type, which can lead to it using the wrong signature.

Move the function matching into a separate function to avoid a label on the loop so we can `break` correctly.

### CODE REVIEW

**Review by abhinav — APPROVED** [review]
thanks!
mind adding an entry to the changelog? (changie new)

File: enforce.go [hunk 1]
```diff
@@ -149,16 +149,8 @@ func (e *enforcer) isReturnedWithNonNilError(stack []ast.Node) bool {
...
-		switch n := stack[idx].(type) {
-		case *ast.FuncDecl:
-			ftype = n.Type
-		case *ast.FuncLit:
-			ftype = n.Type
-		}
-	}
-	if ftype == nil {
+	ftype, ok := parentFuncType(stack[:retIdx])
+	if !ok || ftype == nil {
```
Comment (ryanhall07) [inline enforce.go:153]: to check my understanding, it should be impossible to hit the nil pointer panic on line 159 because `ftype.Results` should always exist now? 

To be consistent with this impossible check `ftype == nil`, I wonder if we should still guard against it? The one downside to not panicing, is you mask this kind of bug.

**Review by ryanhall07 — APPROVED** [review]

File: enforce.go (hunk 1 above)
Comment (prashantv) [reply enforce.go:153]: I think it should be impossible since this code should only run when returning a struct with required fields, but that requires the function to have non-empty returns (hence `ftype.Results != nil`). That said, the AST would technically allow that (but the type checker would disallow it).

We only ran into that case because the function signature matching was incorrect, but I do think it's worth guarding against a panic in that case, since the code already handles `if len(returnTypes) == 0 {`.

**Review by abhinav — APPROVED** [review]
